name: Deploy to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set executable permissions on Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: |
          echo "$(ls)"
          ./gradlew clean bootJar

      - name: Copy JAR to EC2 instance
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          APP_USER: ubuntu
          APP_HOST: ec2-13-125-87-229.ap-northeast-2.compute.amazonaws.com
        run: |
          echo "$PRIVATE_KEY" > EC2-KEY-PAIR-3.pem
          chmod 600 EC2-KEY-PAIR-3.pem
          scp -i "EC2-KEY-PAIR-3.pem" -o StrictHostKeyChecking=no ./build/libs/demo-0.0.1-SNAPSHOT.jar $APP_USER@$APP_HOST:/home/ubuntu/

      - name: Run the JAR on the EC2 instance
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          APP_USER: ubuntu
          APP_HOST: ec2-13-125-87-229.ap-northeast-2.compute.amazonaws.com
        run: |
          echo "$PRIVATE_KEY" > ec2-key-pair.pem
          chmod 600 EC2-KEY-PAIR-3.pem
          ssh -i "EC2-KEY-PAIR-3.pem" -o StrictHostKeyChecking=no $APP_USER@$APP_HOST "pkill -f 'java.*demo-0.0.1-SNAPSHOT.jar'; nohup sudo java -jar /home/ubuntu/demo-0.0.1-SNAPSHOT.jar > log.out 2>&1 &"
