
name: Deploy to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run EC2 instance
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > EC2-KEY-PAIR-3.pem
          chmod 600 EC2-KEY-PAIR-3.pem
          ssh -o StrictHostKeyChecking=no -i "EC2-KEY-PAIR-3.pem" ubuntu@ec2-13-209-7-237.ap-northeast-2.compute.amazonaws.com
      
      - name: Set executable permissions on Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: |
          echo "$(ls)"
          ./gradlew clean bootJar
          
      - name: Transfer JAR to EC2
        run: |
          chmod 600 EC2-KEY-PAIR-3.pem
          scp -i "EC2-KEY-PAIR-3.pem" ./build/libs/demo-0.0.1-SNAPSHOT.jar ubuntu@ec2-13-209-7-237.ap-northeast-2.compute.amazonaws.com:/home/ubuntu/demo-0.0.1-SNAPSHOT.jar

      - name: Run the JAR on the EC2 instance
        run: |
          echo "$(ls)"
          ssh -i "EC2-KEY-PAIR-3.pem" ubuntu@ec2-13-209-7-237.ap-northeast-2.compute.amazonaws.com -exec sudo java -jar demo-0.0.1-SNAPSHOT.jar
